# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63e4b54dfca10dad35b7f0195d68731a0346eb39d64873045973a3d4cc17884abb7dc9f692335b814f1e731451cb5e516e9b2fa986c4e895a25587b02437d3d6

test:
  secret_key_base: 9a9012d7cdff8ee51074d726ed2eecbc73c7ad837df1847c4f7dfdf52bbfab52ae91c41ab3dbb11640cfd6db2d7093c74775b3a3263f8654842dac1f003fd9dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
